skip_tags: true
test_script:
    - gradlew build --no-daemon
after_test:
    - ps: ./uploadTestResults.ps1
build: off
artifacts:
    - path: build/reports/tests/test/**/*.*
    - path: build/reports/tests/functionalTest/**/*.*
